image: jackfirth/racket:7.0

variables:
  LC_ALL: C.UTF-8
  FONTCONFIG_PATH: /etc/fonts


before_script:
  - export FONTCONFIG_PATH=/etc/fonts
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install libglib2.0-0 -y
  - apt-get install libpango-1.0-0 -y
  - apt-get install ttf-liberation -y
  - apt-get install libpangocairo-1.0-0 -y
  - apt-get install libcairo2 -y
  - apt-get install libjpeg62 -y
  - apt-get install libpng16-16 -y
  - raco pkg install --deps search-auto plot
  - fc-list


pages:
  stage: deploy
  script:
  - make pages
  artifacts:
    paths:
    - public
  only:
  - master