image: jackfirth/racket:7.0

variables:
  LC_ALL: C.UTF-8


before_script:
  - raco pkg install plot


pages:
  stage: deploy
  script:
  - make pages
  artifacts:
    paths:
    - public
  only:
  - master